version: '3.5'

networks:
  forum-network:

volumes:
  forum-pg-data:


services:
  postgres:
    image: postgres
    container_name: forum_pg
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - forum-pg-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432/tcp
    networks:
      - forum-network
  forum:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: forum
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      API_ADDR: ${API_ADDR}
      API_W_TIMEOUT: ${API_W_TIMEOUT}
      API_R_TIMEOUT: ${API_R_TIMEOUT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    env_file:
      - .env
    networks:
      - forum-network